### ISSUE TITLE
Strange evaluation order

### ISSUE THREAD

**Issue by Youka** [chmln/asciimath-rs#7]
`assert_eq!(eval("abs(x + 1)", &scope!{"x" => -5}), Ok(4.0));`
...panics with...
```
  left: `Ok(6.0)`,
 right: `Ok(4.0)`
```

`assert_eq!(eval("my_sum(2,3*2)", &scope!{ "my_sum" => (|args| Ok(args.iter().sum())) as CustomFn }), Ok(8.0));`
...panics with...
```
  left: `Ok(10.0)`,
 right: `Ok(8.0)`
```

Not what i expected :/

**Comment by chmln** [comment]
Thanks a lot for reporting this @Youka.
I have released v0.8.8 with the fix.
